name: Apply
on:
  push:
    branches:
    - main
env:
  GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}
  GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
  GEM_HOST_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
jobs:
  oruka:
    permissions:
      actions: write
      checks: write
      contents: write
      deployments: write
      issues: write
      packages: write
      pull-requests: write
      repository-projects: write
      security-events: write
      statuses: write
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0.3'
    - name: Deploy
      run: |
        git config --global user.name "$GIT_USER_NAME"
        git config --global user.name "$GIT_USER_EMAIL"
        bundle install
        bundle exec rake release