name: Plan
on:
  pull_request:
    branches:
    - main
jobs:
  oruka:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0.3'
    - name: Build
      run: |
        bundle install
    - name: Test
      run: |
        bundle exec rspec
        bundle exec rubocop